# Docker File for destreamer

FROM ubuntu
ENV TZ=Europe/London
RUN apt-get update && apt-get upgrade -y
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y install libnss3 libcups2 gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 \
libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst \
ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget curl gnupg git nodejs npm ffmpeg
RUN mkdir /download
RUN chmod 777 /download
RUN useradd -ms /bin/bash destreamer
RUN git clone https://github.com/snobu/destreamer
WORKDIR destreamer
RUN apt-get -y install chromium-browser
RUN npm install
RUN npm run build
USER destreamer
