version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /root/nextcloud:/config
      - /root/nextcloud:/data
    ports:
      - ####:443
    restart: unless-stopped
